version: "3.9"

services:
  # ------------------------------------------------------------
  # NodeJS + Sqlite3 - Backend
  # ------------------------------------------------------------
  backend:
    container_name: backend
    build:
      context: ./src/backend
    hostname: backend
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./src/backend/src:/usr/src/app/src
    networks:
      - redtetris-network
    restart: unless-stopped

  # ------------------------------------------------------------
  # React 18 - Frontend
  # ------------------------------------------------------------
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    environment:
      WATCHPACK_POLLING: "true"
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend
    volumes:
      - ./src/frontend/src:/usr/src/app/src
    networks:
      - redtetris-network
    restart: unless-stopped

volumes:
  dbdata:

networks:
  redtetris-network:
    driver: bridge
