name: Red-Tetris CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRONTEND_PORT: 3000
      BACKEND_PORT: 5000

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - name: Backend checking
        run: cd ./src/backend && npm i && npm run test

      - name: Frontend checking
        run: cd ./src/frontend && npm i && npm run test

